version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: vaultpay-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: vaultpay
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vaultpay"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: vaultpay-cache
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  vaultpay-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vaultpay-service
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secretpassword
      DB_NAME: vaultpay
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    # 🔥 MOUNTED THE CRYPTOGRAPHIC PEM KEYS INTO THE APPLICATION CONTAINER WORKING DIRECTORY:
    volumes:
      - .:/app
      - ./private_key.pem:/app/private_key.pem
      - ./public_key.pem:/app/public_key.pem

  # 📊 PROMETHEUS
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: vaultpay-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - vaultpay-api

  # 📉 GRAFANA
  grafana:
    image: grafana/grafana:10.2.0
    container_name: vaultpay-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  # 📑 SWAGGER UI DOCUMENTATION GATEWAY
  # 📑 SWAGGER UI DOCUMENTATION GATEWAY
  vaultpay-docs:
    image: swaggerapi/swagger-ui:v5.11.0
    container_name: vaultpay-swagger-gateway
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /swagger.yml
    volumes:
      - ./docs/swagger.yml:/swagger.yml
    depends_on:
      - vaultpay-api

# Global storage volumes
volumes:
  pgdata: