apiVersion: v1
kind: Secret
metadata:
  name: vaultpay-crypto-certs
type: Opaque
stringData:
  # Open your private_key.pem file and copy/paste its COMPLETE content below:
  private_key.pem: |
    -----BEGIN RSA PRIVATE KEY-----
    YOUR_MULTILINE_PRIVATE_KEY_CONTENT_GOES_HERE
    -----END RSA PRIVATE KEY-----

  # Open your public_key.pem file and copy/paste its COMPLETE content below:
  public_key.pem: |
    -----BEGIN PUBLIC KEY-----
    YOUR_MULTILINE_PUBLIC_KEY_CONTENT_GOES_HERE
    -----END PUBLIC KEY-----